echo Press any key to start the installation Service...
echo The original clean-up services...
sc delete "FileMonitorService"
echo Clean-up completed, start the installation of Service Backgrounds...
sc create "FileMonitorService" binpath= %cd%\WindowsServiceDemo.exe type= own start= auto DisplayName= "FileMonitorService"
echo Services installed, start the Service...
net start "FileMonitorService"
echo Ending operation, please view InstallService.log specific operating results.
echo press any key
pause
exit