echo Press any key to start the installation Service...
echo The original clean-up services...
net stop "FileMonitorService"
sc delete "FileMonitorService"
echo Clean-up completed, start the installation of Service Backgrounds...
echo press any key
pause
exit